app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("mytest")

app$setInputs(`states_ui_1-state` = "South Dakota")
app$setInputs(`counties_ui_1-state_4_counties` = "South Dakota")
app$snapshot()
app$setInputs(navbar = "States")
app$setInputs(`states_ui_1-state` = c("South Dakota", "Ohio"))
app$setInputs(`states_ui_1-state` = c("South Dakota", "Ohio", "New Jersey"))
app$setInputs(`states_ui_1-cases_deaths` = "0")
app$setInputs(navbar = "Counties")
app$setInputs(navbar = "Vaccinations")
app$setInputs(`vaccinations_ui_1-map_2` = "2")
app$snapshot()
app$setInputs(navbar = "Data and Methodology")
